spring:
  datasource:
    url: jdbc:h2:file:./data/database
    driver-class: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 30MB
files:
  upload:
    uploadPath: upload